2022-10-12 12:28:05,945 INFO    MainThread:8492 [wandb_setup.py:_flush():68] Configure stats pid to 8492
2022-10-12 12:28:05,945 INFO    MainThread:8492 [wandb_setup.py:_flush():68] Loading settings from C:\Users\AsadMehmood\.config\wandb\settings
2022-10-12 12:28:05,946 INFO    MainThread:8492 [wandb_setup.py:_flush():68] Loading settings from C:\Users\AsadMehmood\OneDrive - kyndryl\Python Scripts\mlops_work\MLOps-Training\08 ECR\outputs\2022-10-12\12-27-44\wandb\settings
2022-10-12 12:28:05,946 INFO    MainThread:8492 [wandb_setup.py:_flush():68] Loading settings from environment variables: {'_require_service': 'True'}
2022-10-12 12:28:05,947 INFO    MainThread:8492 [wandb_setup.py:_flush():68] Inferring run settings from compute environment: {'program_relpath': '08 ECR\\train.py', 'program': 'C:\\Users\\AsadMehmood\\OneDrive - kyndryl\\Python Scripts\\mlops_work\\MLOps-Training\\08 ECR\\train.py'}
2022-10-12 12:28:05,948 INFO    MainThread:8492 [wandb_init.py:_log_setup():476] Logging user logs to C:\Users\AsadMehmood\OneDrive - kyndryl\Python Scripts\mlops_work\MLOps-Training\08 ECR\outputs\2022-10-12\12-27-44\wandb\run-20221012_122805-t0clu0eu\logs\debug.log
2022-10-12 12:28:05,949 INFO    MainThread:8492 [wandb_init.py:_log_setup():477] Logging internal logs to C:\Users\AsadMehmood\OneDrive - kyndryl\Python Scripts\mlops_work\MLOps-Training\08 ECR\outputs\2022-10-12\12-27-44\wandb\run-20221012_122805-t0clu0eu\logs\debug-internal.log
2022-10-12 12:28:05,953 INFO    MainThread:8492 [wandb_init.py:init():516] calling init triggers
2022-10-12 12:28:05,954 INFO    MainThread:8492 [wandb_init.py:init():519] wandb.init called with sweep_config: {}
config: {}
2022-10-12 12:28:05,957 INFO    MainThread:8492 [wandb_init.py:init():569] starting backend
2022-10-12 12:28:05,958 INFO    MainThread:8492 [wandb_init.py:init():573] setting up manager
2022-10-12 12:28:06,008 INFO    MainThread:8492 [backend.py:_multiprocessing_setup():102] multiprocessing start_methods=spawn, using: spawn
2022-10-12 12:28:06,061 INFO    MainThread:8492 [wandb_init.py:init():580] backend started and connected
2022-10-12 12:28:06,096 INFO    MainThread:8492 [wandb_init.py:init():658] updated telemetry
2022-10-12 12:28:06,399 INFO    MainThread:8492 [wandb_init.py:init():693] communicating run to backend with 60 second timeout
2022-10-12 12:28:10,613 WARNING MsgRouterThr:8492 [router.py:message_loop():77] message_loop has been closed
2022-10-12 12:28:11,535 ERROR   MainThread:8492 [wandb_init.py:init():1105] error
Traceback (most recent call last):
  File "C:\Anaconda3\envs\tf-torch\lib\site-packages\wandb\sdk\wandb_init.py", line 1078, in init
    run = wi.init()
  File "C:\Anaconda3\envs\tf-torch\lib\site-packages\wandb\sdk\wandb_init.py", line 697, in init
    result = handle.wait(
  File "C:\Anaconda3\envs\tf-torch\lib\site-packages\wandb\sdk\lib\mailbox.py", line 259, in wait
    raise MailboxError("transport failed")
wandb.errors.MailboxError: transport failed
